[package]
name = "kernel"
version = "0.1.0"
edition = "2024"
authors = ["31core <31core@tutanota.com>"]
license-file = "LICENSE"

[dependencies]
aes = { path = "crypto/aes" }
crypto_framework = { path = "crypto/crypto_framework" }
